spring.application.name=psiconet-backend
server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

api.security.token.secret=xG86yDgMWnOOMF9D21kci1IU8bcGi6W7Ij5kdq7kaiO

spring.datasource.url=jdbc:postgresql://localhost:5432/psiconet
spring.datasource.username=psiconet_db
spring.datasource.password=psiconet010203

# Parametros do usuario ADMIN inicial
BASE_EMAIL=admin@psiconet.com
BASE_PASSWORD=psiconet123