package com.psiconet.model.enums;

public enum NotificationType {
    APPOINTMENT_SCHEDULED,
    APPOINTMENT_CANCELLED,
    CONNECTION_REQUESTED,
    CONNECTION_ACCEPTED,
    PAYMENT_PENDING,
    PAYMENT_RECEIPT_SUBMITTED,
    PAYMENT_APPROVED,
    PAYMENT_REJECTED,
    PAYMENT_DISPUTED
}